# Generated by Django 3.2.9 on 2023-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_auto_20230509_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='phone',
            field=models.IntegerField(max_length=104),
        ),
    ]
